SCENARIO_ID_Shop = 1
SCENARIO_ID_Bar = 2

CLIENT_INITIAL_BALANCE = 1000

BIG_SHOW_INTERVAL_SECONDS = 60
BIG_SHOW_SIMPLATE_TIMEOUT_SECONDS = 15 

SIMPLE_ID_BIG_SHOW = "big_show"
SIMPLE_ID_FEEDBACK = "happy_metter"

#MAKE_VIP_CLIENTS = True
MAKE_VIP_CLIENTS = False 
